spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.101:3306/db
    username: root
    password: 123456
  data:
    redis:
      host: 192.168.56.101
      port: 6379