server:
  port: 9002
spring:
  application:
    name: main
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nocos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/li88qq
    username: root
    password: 1234
  redis:
    lettuce:
      pool:
        enabled: true
    host: 192.168.56.95
    port: 6379
img:
  path: d:/img
mqtt:
  username: admin
  password: public
  server: tcp://192.168.56.95:1883

seata:
  config:
    type: nacos
    nacos:
      server-addr: 192.168.56.100:8848
      group: "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.56.100:8848
      group: "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
      cluster: "default"
  
